rbls {
  abusix_noip {
    symbol = "RBL_AMI_NOIP";
    rbl = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.noip.mail.abusix.zone";
    checks = [ "from", "received" ];
  }

  abusix_dblack {
    symbol = "RBL_AMI_DBLACK";
    rbl = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dblack.mail.abusix.zone";
    checks = [ "content_urls", "dkim" ];
    selector = "urls:get_host";
  }

  abusix_nod {
    symbol = "RBL_AMI_NOD";
    rbl = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.nod.mail.abusix.zone";
    checks = [ "content_urls", "dkim", "urls" ];
  }

  SURBL_MULTI {
    ignore_defaults = true;
    rbl = "multi.surbl.org";
    checks = ["emails", "dkim", "urls"];
    emails_domainonly = true;
    urls = true;
    returnbits {
      ABUSE_SURBL = 64;
      MW_SURBL_MULTI = 16;
      PH_SURBL_MULTI = 8;
      DM_SURBL = 4;
    }
  }

  URIBL_MULTI {
    ignore_defaults = true;
    rbl = "multi.uribl.com";
    checks = ["emails", "dkim", "urls"];
    emails_domainonly = true;
    returnbits {
      URIBL_BLACK = 2;
      URIBL_GREY = 4;
      URIBL_RED = 8;
    }
  }

  RSPAMD_URIBL {
    ignore_defaults = true;
    rbl = "uribl.rspamd.com";
    checks = ["emails", "dkim", "urls"];
    images = true;
    emails_domainonly = true;
    hash = "blake2";
    hash_len = 32;
    hash_format = "base32";
    returncodes {
      RSPAMD_URIBL = ["127.0.0.2"];
    }
  }
}
